services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: mobo_postgres
    environment:
      POSTGRES_DB: mobo
      POSTGRES_USER: mobo
      POSTGRES_PASSWORD: mobo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mobo -d mobo"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build: .
    container_name: mobo_bot
    environment:
      - DATABASE_URL=postgresql+asyncpg://mobo:mobo@postgres:5432/mobo
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: ["python", "-m", "bot.main"]

volumes:
  postgres_data: